### ISSUE TITLE
Finish all stories and documentation for v1.0.0

### ISSUE THREAD

**Issue by Portals** [cthit/react-digit-components#108]

**Comment by ViddeM** [comment]
Examples of components I believe could use some (more) documentation: 

### Could use a code example:
    - [ ] DigitAutocompleteSelect 
    - [ ] DigitAutocompleteSelectMultiple
    - [ ] DigitDateAndTimePicker
    - [ ] DigitRenderSelector

### (Currently) no documentation at all that I could find.
    - [ ] DigitAvatar
    - [ ] DigitImage
    - [ ] DigitStepper
    - [ ] DigitComponentSelector
    - [ ] DigitContainUser
    - [ ] DigitTableCheckboxes (Was broken in storybook as well).

Apart from this DigitTable was also broken in the storybook.

// Love, your admin <3

**Comment by Portals** [comment]
This will use Storybooks new docs addon. So we're waiting a bit for this. 

https://docs.google.com/document/d/1un6YX7xDKEKl5-MVb-egnOYN8dynb5Hf7mq0hipk8JE/edit?pli=1#

**Comment by Portals** [comment]
# Declaratives
- [ ] DigitProviders: Misses a story. 

# Elements
- [ ] DigitAutocompleteSelectMultiple: 
    - [ ] Misses props
    - [ ] More examples
    - [ ] Description
- [ ] DigitAutocompleteSelectSingle: 
    - [ ] Misses props
    - [ ] More examples
    - [ ] Description
- [ ] DigitAvatar
    - [ ] Description
- [X] DigitBottomNavigation
- [ ] DigitButtonGroup
    - [ ] Description
    - [ ] More examples
- [ ] DigitButton
    - [ ] Misses prop types description
- [ ] DigitCheckbox
    - [ ] Incorrect description
- [ ] DigitChip
    - [ ] Description
- [ ] DigitCustomDialog
    - [ ] Story
    - [ ] Props
- [ ] DigitDateAndTimePicker
    - [ ] Props
    - [ ] Incorrect description
- [ ] DigitDatePicker 
    - [ ] Props
    - [ ] Incorrect description
- [ ] DigitDialog
    - [ ] Story
- [ ] DigitDisplayData
    - [ ] Incorrect description
- [ ] DigitEditDataCard 
    - [ ] Incorrect description
- [ ] DigitEditData
    - [ ] Incorrect description
- [X] DigitFAB
- [X] DigitIconButton
- [ ] DigitListSelectMultiple
    - [ ] Incorrect props
    - [ ] More examples
    - [ ] Description
- [ ] DigitListSelectSingle
    - [ ] Incorrect props
    - [ ] More examples
    - [ ] Description
- [ ] DigitList
    - [ ] Incorrect props
    - [ ] More examples
    - [ ] Description
-  [X] DigitLoading
- [ ] DigitMarkdown
    - [ ] More markdown examples
- [ ] DigitRadioButtonGroup
    - [ ] Incorrect description
- [ ] DigitSelect
    - [ ] Incorrect description
- [ ] DigitStepper 
    - [ ] Description
- [ ] DigitSwitch
    - [ ] Incorrect description
- [X] DigitTabs
- [ ] DigitTextArea
     - [ ] Bork story
- [ ] DigitTextField
     - [ ] Bork story
- [ ] DigitTimePicker
     - [ ] Props
     - [ ] Incorrect description
- [X] DigitTooltip

# Hooks
- [ ] useDigitCustomDialog
   - [ ] Description
   - [ ] Props
   - [ ] More examples
- [ ] useDigitDialog
   - [ ] Description
   - [ ] Props
   - [ ] More examples
- [ ] useDigitFormFieldArray
   - [ ] Story
- [ ] useDigitFormField
   - [ ] Story
- [ ] useDigitToast
   - [ ] Description
   - [ ] Props
   - [ ] More examples
- [ ] useDigitTranslations
    - [ ] Story
- [ ] useGamma
    - [ ] Story
- [ ] useGammaUsers
    - [ ] Story

# Styles
- [ ] DigitDesign - Card
- [ ] DigitLayout
    - [ ] Stories for everything
- [ ] DigitText
    - [ ] Stories

# Views
- [ ] DigitCalendar
    - [ ] Fix story
    - [ ] Description
    - [ ] Props
- [ ] DigitCRUD
    - [ ] Description
    - [ ] Finish props
- [ ] DigitForm
    - [ ] Story
- [ ] DigitHeader
    - [ ] Story
- [ ] DigitMenu
    - [ ] Story
- [ ] DigitTable
    - [ ] Story

**Comment by Portals** [comment]
Just going to go through all the prop types comments again, other then that, documentation is done!

**Comment by Portals** [comment]
Great work @Hoidi!
