### ISSUE TITLE
DigitIconButton noClick event is called on render

### ISSUE THREAD

**Issue by Epiq99** [cthit/react-digit-components#213]
The onClick event is suppose to trigger when the user clicks the icon button (makes sense right?), but instead it is triggered when the button is rendered.

This resulted in all my entries in my database to be deleted when i added a delete icon button to each entry. XD

**Comment by Portals** [comment]
Can I see code when you're using DigitIconButton?

**Comment by Epiq99** [comment]
```
<div className ="card">
      <div className="innerCard">
        <Grid container >
          <Grid item xs={10}>
            <DigitNavLink text={suggestion.title} link={"/suggestion/" + suggestion.id}/>
          </Grid>
          <Grid item xs={1}>
            <DigitIconButton icon={Clear} onClick= {deleteSuggestion(suggestion.id)}/>
          </Grid>
        </Grid>
        <section>
          <DigitText.Subtitle2 text={suggestion.author} className = "authorLabel"/>
          <DigitText.Subtitle2 text={translateTimestamp(ts)} className = "timeStampLabel"/>
          {text}
        </section>
      </div>
    </div>
```

**Comment by Epiq99** [comment]
I tested with DigitButton just now, and it also triggered on render

**Comment by Portals** [comment]
You are not providing a function to onClick. You're providing whatever deleteSuggestion is returning. Please wrap it in () => delete..... to achieve your wanted behavior.

**Comment by Epiq99** [comment]
Oh, thank you. That works!
