### ISSUE TITLE
Attempted import error

### ISSUE THREAD

**Issue by Flakt** [cthit/react-digit-components#225]
Trying to compile a project using react-digit-components results in:
```
./node_modules/@cthit/react-digit-components/dist/index.es.js
Attempted import error: 'useDispatch' is not exported from 'react-redux'.
```

**Comment by Portals** [comment]
can I see your package.json?

**Comment by Portals** [comment]
also the code when you're importing useDispatch

**Comment by Flakt** [comment]
```  
"@cthit/react-digit-components": "^1.0.0-beta.13",
```

**Comment by Hoidi** [comment]
Please use a newer version. Latest it beta.41

**Comment by Portals** [comment]
Also upgrade your react-redux version, useDispatch isn't introduced until 7.0.0. Se peer dependencies in package.json for rdc for the correct package versions
