### ISSUE TITLE
Dissapearing text in readme

### ISSUE THREAD

**Issue by ViddeM** [cthit/react-digit-components#265]
In the README.md file on line 38 (in the markdown) the text ```<head></head>``` exists, however it is not shown in the displayed version of the file making the sentance end on "..., in the tag."

**Comment by Portals** [comment]
DigitMarkdown is a mess right now. A major refactoring is needed

**Comment by ViddeM** [comment]
This is on the github page. :P

**Comment by Portals** [comment]
Closing since README.md is pretty much gone
