### ISSUE TITLE
Title dissapears from DigitNavigation when switching to "wide-mode".

### ISSUE THREAD

**Issue by ViddeM** [cthit/react-digit-components#30]
Is this intentional?

**Comment by Portals** [comment]
Can't reproduce in Storybook, could you provide a photo? Something worth noting, `DigitNavigation` will be renamed to `DigitHeader` in #22, with the option to not have a drawer.

**Comment by ViddeM** [comment]
![no_title](https://user-images.githubusercontent.com/16452604/45948986-601c5980-bffa-11e8-88e6-c5787de6896d.png)


I believe it's fallen behind the drawer.

**Comment by Portals** [comment]
Looks like the header div hasn't got any padding-left. For some reason the hamburger menu is showed as well...

**Comment by Portals** [comment]
The problem is that material-ui isn't loaded before styled components, which react-digit-components uses. This is the code that is needed in the <head></head> is the following:

```
