### ISSUE TITLE
DigitDateAndTimePicker requires Date but appears to only take string?

### ISSUE THREAD

**Issue by ViddeM** [cthit/react-digit-components#320]
https://github.com/cthit/react-digit-components/blob/f0442797657d6011fed9afc9d21d4755fde12f26/src/elements/digit-date-and-time-picker/DigitDateAndTimePicker.element.jsx#L115

**Comment by ViddeM** [comment]
https://github.com/cthit/react-digit-components/blob/f0442797657d6011fed9afc9d21d4755fde12f26/src/elements/digit-date-and-time-picker/DigitDateAndTimePicker.element.jsx#L80

**Comment by Portals** [comment]
That's not the same thing. It's how @material-ui/pickers formats their strings
