### ISSUE TITLE
DigitTextArea rows doesn't work.

### ISSUE THREAD

**Issue by ViddeM** [cthit/react-digit-components#353]
![image](https://user-images.githubusercontent.com/16452604/79219368-6e3b0080-7e52-11ea-9bdd-55a41ac6c54a.png)

for the following code, note that rows is set to 10 but only 6 is shown.

```javascript
<DigitTextArea
    value={config.value}
    outlined
    upperLabel={config.key}
    size={{
      width: "100%"
    }}
    rows={10}
    onChange={e => props.onConfigChange(config.key, e.target.value)}
/>
```

**Comment by Portals** [comment]
Will be closed by v1.0.1
