### ISSUE TITLE
Add option to toggle visibility of DigitHeaderDrawer

### ISSUE THREAD

**Issue by ericlp** [cthit/react-digit-components#433]

**Comment by ViddeM** [comment]
Can't you do something like:
```renderDrawer={() => {
    drawerEnabled && (
        <Drawer />    
    )
}}```?

**Comment by ericlp** [comment]
Not really, renderDrawer is a required parameter so it has to be given something and the main problem lies in that the The entire digitHeader has internal Mediaqueries that adjust its layout according to the size of the screen. I think the best way forward is to supply an alternative DigitDrawerAlwaysToggle. To achieve both functionalities in the same component may produce to complex spaghetti  code.

**Comment by Portals** [comment]
Closing. Currently released under `v1.0.4-alpha.1`.
